### ISSUE TITLE
【单元测试】:全局方法引入 

### ISSUE THREAD

**Issue by blackcloud2333** [maxpou/vue-vuex-jest#14]
如果组件a引入了组件b,组件b需要全局的某些方法（此全局方法为自己封装的），
那么如何才能引入此全局方法，完成a单元测试呢？
现在a在测试的时候报错，无法读取到某个属于全局方法获取的属性
尝试解决方案
1  尝试在a的单元测试当中引入此全局方法
   因为客观原因无法打包此全局方法，所以vue.use（）无法使用
2 尝试在window上挂载此属性，但是报错，无法设置此属性为undefined
3 尝试spyon去模拟此方法，但是感觉场景不合适
求问大佬有没有解决方案

**Comment by maxpou** [comment]
English only please.
